package com.campus360.ai.service;

import com.campus360.ai.AiClient;
import com.campus360.placement.domain.JobPosting;
import com.campus360.placement.eligibility.EligibilityEngine;
import com.campus360.placement.eligibility.EligibilityResult;
import com.campus360.placement.repository.JobPostingRepository;
import com.campus360.platform.error.ApiException;
import com.campus360.platform.tenancy.TenantContext;
import com.campus360.student.domain.StudentProfile;
import com.campus360.student.repository.StudentProfileRepository;
import org.springframework.stereotype.Service;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

/**
 * Campus360 Intelligence. The readiness score is computed deterministically so
 * it is explainable and works offline; the narrative coaching and rationale are
 * generated by the configured {@link AiClient} (OpenAI when enabled).
 */
@Service
public class CareerIntelligenceService {

    private static final String SYSTEM = """
            You are a university placement and career advisor. Be concrete, encouraging and
            actionable. Keep responses under 200 words. Never invent facts about the student
            beyond what is provided.""";

    private final StudentProfileRepository students;
    private final JobPostingRepository postings;
    private final EligibilityEngine eligibilityEngine;
    private final AiClient ai;

    public CareerIntelligenceService(StudentProfileRepository students, JobPostingRepository postings,
                                     EligibilityEngine eligibilityEngine, AiClient ai) {
        this.students = students;
        this.postings = postings;
        this.eligibilityEngine = eligibilityEngine;
        this.ai = ai;
    }

    public ReadinessReport readiness(Long studentId) {
        StudentProfile s = student(studentId);
        List<String> factors = new ArrayList<>();

        // CGPA contributes up to 60 points.
        int cgpaPoints = s.getCgpa()
                .multiply(BigDecimal.valueOf(6))
                .min(BigDecimal.valueOf(60))
                .intValue();
        factors.add("CGPA " + s.getCgpa() + " -> " + cgpaPoints + "/60");

        // Backlogs penalise up to -20.
        int backlogPenalty = Math.min(s.getActiveBacklogs() * 10, 20);
        if (backlogPenalty > 0) {
            factors.add(s.getActiveBacklogs() + " active backlog(s) -> -" + backlogPenalty);
        }

        // Profile completeness contributes up to 40.
        int completeness = 0;
        if (s.getBranch() != null && !s.getBranch().isBlank()) {
            completeness += 15;
        } else {
            factors.add("Branch not set -> missing 15");
        }
        if (s.getBatchYear() != null) {
            completeness += 10;
        } else {
            factors.add("Batch year not set -> missing 10");
        }
        if (s.getProgramId() != null) {
            completeness += 15;
        } else {
            factors.add("Program not linked -> missing 15");
        }

        int score = Math.max(0, Math.min(100, cgpaPoints - backlogPenalty + completeness));
        String band = score >= 75 ? "STRONG" : score >= 50 ? "DEVELOPING" : "AT_RISK";

        String coaching = ai.complete(SYSTEM, """
                A student has a placement readiness score of %d/100 (band: %s).
                Profile: CGPA %s, active backlogs %d, branch %s, batch %s.
                Contributing factors: %s.
                Give a short, prioritised improvement plan to raise their readiness."""
                .formatted(score, band, s.getCgpa(), s.getActiveBacklogs(),
                        s.getBranch(), s.getBatchYear(), String.join("; ", factors)));

        return new ReadinessReport(studentId, score, band, factors, coaching, ai.isLive());
    }

    public String resumeFeedback(Long studentId, String resumeText) {
        StudentProfile s = student(studentId);
        if (resumeText == null || resumeText.isBlank()) {
            throw ApiException.badRequest("resumeText is required");
        }
        return ai.complete(SYSTEM, """
                Review this student's resume and give specific, prioritised improvements
                (structure, impact, quantification, keywords). Student branch: %s, CGPA %s.

                RESUME:
                %s""".formatted(s.getBranch(), s.getCgpa(), resumeText));
    }

    public String mockInterview(Long studentId, String role) {
        StudentProfile s = student(studentId);
        String target = (role == null || role.isBlank()) ? "a software engineering role" : role;
        return ai.complete(SYSTEM, """
                Generate 5 tailored mock interview questions for a campus candidate
                targeting %s. Student branch: %s, CGPA %s. Mix technical, behavioural and
                one situational question, and add a one-line tip on what a strong answer covers."""
                .formatted(target, s.getBranch(), s.getCgpa()));
    }

    public JobFitReport jobFit(Long studentId, Long postingId) {
        Long tenant = TenantContext.requireTenantId();
        StudentProfile s = student(studentId);
        JobPosting posting = postings.findByIdAndTenantId(postingId, tenant)
                .orElseThrow(() -> ApiException.notFound("Posting not found: " + postingId));

        EligibilityResult result = eligibilityEngine.evaluate(
                eligibilityEngine.parse(posting.getEligibility()), s);

        String explanation = ai.complete(SYSTEM, """
                Assess fit between a student and a job posting.
                Posting: %s (%s), CTC %s, location %s.
                Student: branch %s, CGPA %s, active backlogs %d, batch %s.
                Eligible: %s. Eligibility gaps: %s.
                Explain the fit and the top skill gaps to close before applying."""
                .formatted(posting.getTitle(), posting.getType(), posting.getCtc(), posting.getLocation(),
                        s.getBranch(), s.getCgpa(), s.getActiveBacklogs(), s.getBatchYear(),
                        result.eligible(), String.join("; ", result.reasons())));

        return new JobFitReport(studentId, postingId, result.eligible(), result.reasons(),
                explanation, ai.isLive());
    }

    private StudentProfile student(Long studentId) {
        return students.findByIdAndTenantId(studentId, TenantContext.requireTenantId())
                .orElseThrow(() -> ApiException.notFound("Student not found: " + studentId));
    }
}
